-- Generated by scripts/gen_migration.py from src/deepresearch/store/models.py.
-- Do not hand-edit — edit models.py and regenerate.
-- Schema: docs/DESIGN.md §4, plus judge_cache (this session's addition,
-- see the comment on that table in models.py for why).

CREATE TABLE runs (
	run_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	benchmark_name VARCHAR, 
	config JSONB NOT NULL, 
	git_sha VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	total_cost_usd NUMERIC(10, 4), 
	total_latency_ms INTEGER, 
	PRIMARY KEY (run_id)
);

CREATE TABLE trajectories (
	id BIGSERIAL NOT NULL, 
	run_id UUID NOT NULL, 
	span_id VARCHAR NOT NULL, 
	parent_span_id VARCHAR, 
	stage VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	input JSONB, 
	output JSONB, 
	tokens_in INTEGER, 
	tokens_out INTEGER, 
	cost_usd NUMERIC(10, 6), 
	latency_ms INTEGER, 
	started_at TIMESTAMP WITH TIME ZONE, 
	ended_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES runs (run_id), 
	UNIQUE (span_id)
);

CREATE TABLE tool_calls (
	id BIGSERIAL NOT NULL, 
	run_id UUID NOT NULL, 
	span_id VARCHAR NOT NULL, 
	tool_name VARCHAR NOT NULL, 
	args JSONB, 
	result_summary JSONB, 
	success BOOLEAN NOT NULL, 
	cache_hit BOOLEAN NOT NULL, 
	latency_ms INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES runs (run_id), 
	FOREIGN KEY(span_id) REFERENCES trajectories (span_id)
);

CREATE TABLE eval_scores (
	id BIGSERIAL NOT NULL, 
	run_id UUID NOT NULL, 
	benchmark_name VARCHAR NOT NULL, 
	question_id VARCHAR, 
	metric_name VARCHAR NOT NULL, 
	value NUMERIC, 
	judge_model VARCHAR, 
	rubric_version VARCHAR, 
	raw_judge_output JSONB, 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES runs (run_id)
);

CREATE TABLE ci_baselines (
	id BIGSERIAL NOT NULL, 
	benchmark_name VARCHAR NOT NULL, 
	metric_name VARCHAR NOT NULL, 
	baseline_value NUMERIC NOT NULL, 
	config JSONB NOT NULL, 
	git_sha VARCHAR NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE judge_cache (
	cache_key VARCHAR NOT NULL, 
	verdict JSONB NOT NULL, 
	judge_model VARCHAR NOT NULL, 
	rubric_version VARCHAR NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (cache_key)
);
