"""Generate db/migrations/0001_init.sql from src/deepresearch/store/models.py.

The SQLAlchemy metadata in store/models.py is the single source of truth for
the schema — this script compiles it against the Postgres dialect so the
migration file can never drift from what the app actually creates via
`init_schema()` in dev/test (SQLite) or CI/deployed (Postgres).

Usage:
    python scripts/gen_migration.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from sqlalchemy.schema import CreateTable  # noqa: E402
from sqlalchemy.dialects import postgresql  # noqa: E402

from deepresearch.store.models import (  # noqa: E402
    ci_baselines,
    eval_scores,
    judge_cache,
    runs,
    tool_calls,
    trajectories,
)

OUT_PATH = Path(__file__).parent.parent / "db" / "migrations" / "0001_init.sql"

TABLES_IN_ORDER = [runs, trajectories, tool_calls, eval_scores, ci_baselines, judge_cache]


def main() -> None:
    dialect = postgresql.dialect()
    statements = [str(CreateTable(table).compile(dialect=dialect)).strip() + ";" for table in TABLES_IN_ORDER]

    header = (
        "-- Generated by scripts/gen_migration.py from src/deepresearch/store/models.py.\n"
        "-- Do not hand-edit — edit models.py and regenerate.\n"
        "-- Schema: docs/DESIGN.md §4, plus judge_cache (this session's addition,\n"
        "-- see the comment on that table in models.py for why).\n"
    )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(header + "\n" + "\n\n".join(statements) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
